name: Node.js CI

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    services: 
      nginx: 
        image: nginx
        ports: 
          - 8080:80
    steps:
    - uses: actions/checkout@v3
    - run: |
        node -v
        curl localhost:8080
